"""
markdown.py — Markdown renderer with optional HTML and PDF conversion.

Outputs:
  - .md  : Raw markdown (always)
  - .html: Styled HTML via Jinja2 template (if requested)
  - .pdf : Via pandoc subprocess (if pandoc is installed)
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from datetime import datetime

from jinja2 import Environment, BaseLoader

# ── HTML Template ─────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ title }} | Auto-Doc Engine</title>
  <style>
    :root {
      --bg: #0d1117; --surface: #161b22; --border: #30363d;
      --text: #c9d1d9; --accent: #58a6ff; --green: #3fb950;
      --red: #f85149; --yellow: #d29922; --code-bg: #1c2128;
      --font-mono: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: var(--bg); color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.7; padding: 2rem;
    }
    .container { max-width: 900px; margin: 0 auto; }
    header {
      border-bottom: 1px solid var(--border); padding-bottom: 1rem;
      margin-bottom: 2rem;
    }
    header .badge {
      display: inline-block; background: var(--accent); color: var(--bg);
      font-size: 0.7rem; font-weight: 700; padding: 2px 8px;
      border-radius: 20px; text-transform: uppercase; letter-spacing: 0.1em;
      margin-right: 0.5rem;
    }
    header .badge.domain { background: var(--green); }
    header .badge.diff { background: var(--yellow); color: #000; }
    h1 { font-size: 1.8rem; font-weight: 700; color: #fff; margin-top: 0.5rem; }
    h2 {
      font-size: 1.1rem; font-weight: 700; color: var(--accent);
      border-bottom: 1px solid var(--border); padding-bottom: 0.4rem;
      margin: 2rem 0 0.8rem;
      text-transform: uppercase; letter-spacing: 0.05em;
    }
    p { margin: 0.6rem 0; }
    ul, ol { padding-left: 1.5rem; margin: 0.5rem 0; }
    li { margin: 0.25rem 0; }
    code {
      font-family: var(--font-mono); font-size: 0.88em;
      background: var(--code-bg); border: 1px solid var(--border);
      padding: 0.1em 0.35em; border-radius: 4px; color: #79c0ff;
    }
    pre {
      background: var(--code-bg); border: 1px solid var(--border);
      border-radius: 8px; padding: 1rem 1.2rem; overflow-x: auto;
      margin: 0.8rem 0; position: relative;
    }
    pre code {
      background: none; border: none; padding: 0;
      color: var(--text); font-size: 0.85rem; line-height: 1.6;
    }
    .pivot {
      border-left: 3px solid var(--red); padding-left: 1rem;
      color: #ff7b72; font-style: italic; margin: 0.5rem 0;
    }
    blockquote {
      border-left: 3px solid var(--border); padding-left: 1rem;
      color: #8b949e; margin: 0.5rem 0;
    }
    strong { color: #fff; }
    .meta {
      font-size: 0.8rem; color: #8b949e; margin-top: 0.5rem;
    }
    footer {
      border-top: 1px solid var(--border); margin-top: 3rem;
      padding-top: 1rem; font-size: 0.75rem; color: #484f58;
      text-align: center;
    }
    table { border-collapse: collapse; width: 100%; margin: 0.8rem 0; }
    th, td { border: 1px solid var(--border); padding: 0.4rem 0.8rem; }
    th { background: var(--surface); color: var(--accent); }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div>
        <span class="badge">CTF Writeup</span>
        <span class="badge domain">{{ domain }}</span>
        <span class="badge diff">{{ difficulty }}</span>
      </div>
      <h1>{{ title }}</h1>
      <div class="meta">Generated by Auto-Doc Engine &nbsp;·&nbsp; {{ generated_at }}</div>
    </header>
    <main>
      {{ body_html }}
    </main>
    <footer>Auto-Doc Engine — Clinical Technical Writeup System</footer>
  </div>
</body>
</html>
"""


def _markdown_to_html_body(md: str) -> str:
    """Convert Markdown to HTML body using the `markdown` library."""
    try:
        import markdown as md_lib

        return md_lib.markdown(
            md,
            extensions=["fenced_code", "tables", "codehilite", "toc"],
        )
    except ImportError:
        # Fallback: wrap in <pre> if markdown library unavailable
        escaped = md.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"<pre>{escaped}</pre>"


def render(
    content: str,
    output_dir: Path,
    slug: str,
    title: str,
    domain: str = "General",
    difficulty: str = "Unknown",
    formats: list[str] | None = None,
) -> dict[str, Path]:
    """
    Write the writeup to all requested output formats.

    Args:
        content:    Raw Markdown string from the AI provider.
        output_dir: Directory to write output files into.
        slug:       Filename stem (e.g., 'web_challenge_01').
        title:      Human-readable challenge name.
        domain:     Security domain label.
        difficulty: Challenge difficulty.
        formats:    List of format strings: ['md', 'html', 'pdf'].

    Returns:
        Dict mapping format string → absolute Path of written file.
    """
    if formats is None:
        formats = ["md", "html", "pdf"]

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    written: dict[str, Path] = {}
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M UTC+05:30")

    # ── Markdown ──────────────────────────────────────────────────────────────
    md_path = output_dir / f"{slug}.md"
    md_path.write_text(content, encoding="utf-8")
    written["md"] = md_path

    # ── HTML ──────────────────────────────────────────────────────────────────
    if "html" in formats or "pdf" in formats:
        body_html = _markdown_to_html_body(content)
        env = Environment(loader=BaseLoader())
        template = env.from_string(_HTML_TEMPLATE)
        html_content = template.render(
            title=title,
            domain=domain,
            difficulty=difficulty,
            generated_at=generated_at,
            body_html=body_html,
        )
        html_path = output_dir / f"{slug}.html"
        html_path.write_text(html_content, encoding="utf-8")
        written["html"] = html_path

    # ── PDF via pandoc ────────────────────────────────────────────────────────
    if "pdf" in formats:
        pandoc = shutil.which("pandoc")
        if pandoc:
            pdf_path = output_dir / f"{slug}.pdf"
            cmd = [
                pandoc,
                str(md_path),
                "-o",
                str(pdf_path),
                "--pdf-engine=xelatex",
                "--highlight-style=breezedark",
                "-V",
                "geometry:margin=1in",
                "-V",
                "colorlinks=true",
                "-V",
                "linkcolor=blue",
                "--toc",
            ]
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode == 0:
                written["pdf"] = pdf_path
            else:
                # Fallback: try wkhtmltopdf on the HTML
                wkhtml = shutil.which("wkhtmltopdf")
                if wkhtml and "html" in written:
                    pdf_path = output_dir / f"{slug}.pdf"
                    subprocess.run(
                        [wkhtml, "--quiet", str(written["html"]), str(pdf_path)],
                        capture_output=True,
                    )
                    if pdf_path.exists():
                        written["pdf"] = pdf_path
        else:
            # pandoc unavailable — note it but don't crash
            written["pdf_skipped"] = Path("pandoc_not_installed")

    return written
